import { readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
const escape = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export async function writeReport(directory:string, report:string) {
  const files=await readdir(directory);
  const states=files.filter(f=>f.endsWith('-browser.png') && files.includes(f.replace('-browser.png','-terminal.png')));
  const cards=states.map(file=>`<section><h2>${escape(file.replace('-browser.png','').replaceAll('-',' '))}</h2><div class="pair"><figure><figcaption>CHROMIUM REFERENCE</figcaption><img src="${file}" loading="lazy"></figure><figure><figcaption>DECODED KITTY FRAME · EXACT PIXEL MATCH</figcaption><img src="${file.replace('-browser.png','-terminal.png')}" loading="lazy"></figure></div></section>`).join('');
  await writeFile(join(directory,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Starpane verification</title><style>*{box-sizing:border-box}body{margin:0;background:#101516;color:#e9eee7;font:15px system-ui;padding:36px;max-width:1500px;margin:auto}header{border-bottom:1px solid #36403e;padding-bottom:24px}h1{font-size:38px;letter-spacing:-1.5px}b{color:#d7ff89}p{color:#a2b6a7;max-width:850px;line-height:1.6}section{margin-top:40px}h2{font-size:19px;font-weight:500}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}figure{margin:0;background:#192120;padding:12px;border:1px solid #36403e;border-radius:8px}figcaption{font-size:10px;letter-spacing:1px;margin:4px 0 14px;color:#a2b6a7}img{display:block;width:100%;height:auto}pre{white-space:pre-wrap;line-height:1.6;color:#a2b6a7;font-size:12px}summary{cursor:pointer}@media(max-width:700px){body{padding:20px}.pair{grid-template-columns:1fr}}</style><header><b>STARPANE / VERIFICATION</b><h1>${report.includes('\nPASS')?'Pixels agree. Interactions pass.':'A check needs attention.'}</h1><p>${states.length} captured states. Each pair compares a browser screenshot with PNG data independently reconstructed from the CLI's real PTY output.</p><p>This proves browser input and lossless frame transport. Native terminal compositing is a separate check: run <code>npm run test:native</code> on macOS with Screen Recording enabled.</p></header>${cards}<section><details><summary>Full execution report</summary><pre>${escape(report)}</pre></details></section></html>`);
}
